POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Docker"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/aadcd74e-7e3c-45ff-8206-4cb4d5bf01bc