POST http://localhost:3333/courses
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZWY2Zjc2Yy1mMmVmLTQyNjQtODRjOS0zMWU1ODllOGViOGYiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTYyMzMwOX0.5a2c-b6n3RibeK2WHRIi09BJMGETUffmMvJ7ICXlyIg

{
  "title": "Curso de Node.js",
  "description": "Descrição do curso de Node.js"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/fa04d35d-58f5-4e34-a78b-e5a2eb264057
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyZWY2Zjc2Yy1mMmVmLTQyNjQtODRjOS0zMWU1ODllOGViOGYiLCJyb2xlIjoibWFuYWdlciIsImlhdCI6MTc1NTYyMzMwOX0.5a2c-b6n3RibeK2WHRIi09BJMGETUffmMvJ7ICXlyIg

###

POST http://localhost:3333/sessions
Content-Type: application/json

{
  "email": "Isaac34@hotmail.com",
  "password": "123456"
}