POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Cu"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/5a28a59d-fc38-4a87-a952-22d6282cddba